### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by tmdsolutions** [tillikum/tillikum#1]
I followed the installation direction and got an error at the ./vendor/bin/phing step with the following error:
.
.
.
Processing entity "Tillikum\Entity\Booking\Facility\Facility"

Proxy classes generated to "/home/doug/work/project/tillikum/data/proxies"

Tillikum > clean:

   [delete] Deleting directory /home/doug/work/project/tillikum/www/document_root/public/build

Tillikum > prepare:

```
[mkdir] Created dir: /home/doug/work/project/tillikum/www/document_root/public/build
```

Tillikum > build-css:

   [append] Attempting to append 6 files, using basedir /home/doug/work/project/tillikum/www/document_root/public/styles
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/normalize.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/html5-boilerplate.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/grids.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/jquery-ui.smoothness.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/jquery.dataTables.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
   [append] Appending contents of /home/doug/work/project/tillikum/www/document_root/public/styles/tillikum.css to /home/doug/work/project/tillikum/www/document_root/public/build/tillikum.css
       [if] Error in IfTask
Execution of target "build-css" failed for the following reason: /home/doug/work/project/tillikum/build.xml:34:8: Argument1 to function must not be null

BUILD FAILED
/home/doug/work/project/tillikum/build.xml:34:8: Argument1 to function must not be null
Total time: 1.1071 second

Thank You,

**Comment by gws** [comment]
@tmdsolutions 

Hi Doug,

I'm sorry, the project has been inactive for some time due to lack of maintainers.

I will add a note to the `README`.

**Comment by gws** [comment]
Closed by https://github.com/tillikum/tillikum/commit/88a2abd9f47958df6fa325057caa1220774410f4
